version: "3"

services:
  backend:
    build:
      dockerfile: Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./static:/code/static
      - ./templates:/code/templates