"""create table for store certificate info

Revision ID: 96a790bdfe43
Revises: 
Create Date: 2024-02-04 16:20:43.182040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96a790bdfe43"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificates",
        sa.Column(
            "uploaded_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "expired_at", sa.DateTime(), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False
        ),
        sa.Column(
            "fingerprint_sha1", sa.String(), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint_sha1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("certificates")
    # ### end Alembic commands ###
